### PR TITLE
Drake/feature/uhf handler

### PR DESCRIPTION
**Pull request by DrakBoul**
Created UHF handler to modify simulated UHF parameters such as beacon and mode.

### CODE REVIEW

**Comment by DrakBoul** [comment]
Should I include functionality to downlink UHF data? For now I'm just logging all information. I figured these logs would be downlinked eventually. Let me know what you would prefer.

**Comment by rrasmuss4200** [comment]
Ideally the BulkMsgDispatcher should be able to read and downlink whichever file the UHF logs are in. Just have to pass it as the message body when sending a command to the BulkMsgDispatcher. As long as its in a directory, it can be downlinked

**Comment by DrakBoul** [comment]
> Ideally the BulkMsgDispatcher should be able to read and downlink whichever file the UHF logs are in. Just have to pass it as the message body when sending a command to the BulkMsgDispatcher. As long as its in a directory, it can be downlinked

Okay, I didn't downlinking those logs. I'll try figure out if I can separate UHF logs and coms handler logs.

**Comment by DrakBoul** [comment]
After further investigation, logging to different directorys within the same binary is more of a challenge then I thought. For now, UHF handler logs are in the same directory (and files) as the coms handler logs.  A new branch implementing a feature like this can be made in the future as it requires additional/rewriting code in the shared logging library which is not in the scope of this PR. Bulk downlinking of data and uplinking commands works as expected, this should be ready to merge after review.

**Review by rrasmuss4200 — CHANGES_REQUESTED** [review]
Great work here Drake. Everything works fine on my end. You've set some great ground work for the UHF. Only thing I'll ask you to do before merging is rebase with main. There wiill be some merge conflicts in there in the scripts with tmux and the common lib

**Comment by rrasmuss4200** [comment]
Dope. Just resolve those last couple merge conflicts then should be good to go

**Pull request closed without merging**
