### PR TITLE
Create SPI HW Interface

### PR DESCRIPTION
**Pull request by DrakBoul**
# Description
#75 
In this PR I created a thin wrapper around the Spidev structure in crate spidev to conform to our Interafce trait. The constructor for the wrapper allows the user to specify a configuration for the device they wish to communicate with, if no config is specified a default config is used.

## Feedback
@rcunrau  In the constructor for the device I return a result, should I even bother? I feel like if a program cannot create the interface we may just want the program to panic. Let me know if this is a scenario where returning a result is not useful.

I am open to any other feedback reviewers have.

### CODE REVIEW

**Comment by rcunrau** [comment]
While I agree that if we can't survive new() we're dad in the water, what you have is OK (and it's what they show in the crate :-) Both open and configure can fail for quasi legitimate reasons (EBUSY, EINTR, EMFILE, EACCESS, etc) and it's important for us to log any failure reasons. I suppose you could log the failure inside new() and then call process::exit(), which would allow you to have Self as the sole return. This also saves the caller from checking for unlikely errors.

**Comment by rcunrau** [comment]
I also see the complaint about "empty line in doc comment" in dfgm, I think. While it's easy enough to remove the line, perhaps we should learn, as a team, what the difference is between /// and //. Then we can decide what internal and external documentation we want, and then we can attempt to make it consistent across all our modules (apologies if we've already done that and I missed it).

**Comment by DrakBoul** [comment]
> I also see the complaint about "empty line in doc comment" in dfgm, I think. While it's easy enough to remove the line, perhaps we should learn, as a team, what the difference is between /// and //. Then we can decide what internal and external documentation we want, and then we can attempt to make it consistent across all our modules (apologies if we've already done that and I missed it).

No we have not actually, and just the other day I learned what "///" does in rust. We should make time for this next meeting, I think it would be helpful.

**Comment by DrakBoul** [comment]
> While I agree that if we can't survive new() we're dad in the water, what you have is OK (and it's what they show in the crate :-) Both open and configure can fail for quasi legitimate reasons (EBUSY, EINTR, EMFILE, EACCESS, etc) and it's important for us to log any failure reasons. I suppose you could log the failure inside new() and then call process::exit(), which would allow you to have Self as the sole return. This also saves the caller from checking for unlikely errors.

Okay that makes sense.

**Review by rcunrau — APPROVED** [review]
Interesting it passes the clippy check, yet there are lots of clippy warnings in the code. As long as it passes, I'm happy enough to merge this PR, but I also wouldn't be upset if you added another commit that cleaned it all up. We'll get to them all eventually...

**Pull request merged**
