### PR TITLE
Created basic JSON housekeeping module

### PR DESCRIPTION
**Pull request by DrakBoul**
No issue for this PR.

This PR introduces a basic housekeeping module that allows subsystems to easily create and write JSON structure to files using helper functions, it also includes functionality to read the files back into JSON structures, and creating a JSON structure that contains subsystem ID and the UTC time when the housekeeping structure was created.

I'm sure this module can be improved upon once we define how housekeeping files should look like. I am open to any feedback.

### CODE REVIEW

**Comment by rcunrau** [comment]
What is that "merge branch 'main' into ..." about? The usual flow is that your branch gets merged into main once it's approved, not the other way around. Normally we would kill the PR and start over if an accident like this happens. Are you able to do that?

**Comment by rrasmuss4200** [comment]
I think that was too solve any merge conflicts before bringing the JSON changes into main.

These changes look like a good start for a HK library with JSON. 
Just to clarify, the plan is in the future to add subsystem specific JSON structure based on the HK/telemetry that's relevant to that subsystem?

**Comment by rcunrau** [comment]
The way to work through conflicts, if there are any, is to "git pull --rebase" in the branch, and resolve the each conflict reported. Note the "--rebase" is critical, otherwiseyou wind up with what we've got - all of main merged onto each branch.

**Comment by DrakBoul** [comment]
> The way to work through conflicts, if there are any, is to "git pull --rebase" in the branch, and resolve the each conflict reported. Note the "--rebase" is critical, otherwiseyou wind up with what we've got - all of main merged onto each branch.

Thanks for letting me know, I did not know this was an issue. I'll fix it asap with a new pr.

**Comment by DrakBoul** [comment]
> I think that was too solve any merge conflicts before bringing the JSON changes into main.
> 
> These changes look like a good start for a HK library with JSON. Just to clarify, the plan is in the future to add subsystem specific JSON structure based on the HK/telemetry that's relevant to that subsystem?

@rrasmuss4200, yes I imagine that each handler will use the library to create a housekeeping file. The strucutre of housekeeping has not been determined yet, but i assume we would like some basic information such as the subsystem id and the utc timestamp of when the file was created. I created a spreadsheet where we will define all the housekeeping items for each susbsystem handler.

**Pull request closed without merging**
