### PR TITLE
Rcunrau/cli poll

### PR DESCRIPTION
**Pull request by rcunrau**

### CODE REVIEW

**Comment by rrasmuss4200** [comment]
This breaks downlink again. Seems to be stalled in the coms handler and no messages are getting through from coms to gs.

Also, can't send a command to the DFGM. It crashes on line 81 since gs_interface is a None value...

**Review by DrakBoul — COMMENTED** [review]
Looks good, thanks a bunch for cleaning up the groundstation code. I created a [branch](https://github.com/AlbertaSat/ex3_software/tree/drake/fix-downlink) that fixes downlink. The cause of downlink not working was a blocking read call on the tcp client connecting to the UHF.  The fix is small and temporary, and should be enough for your branch to be approved and merged. Before a permanant fix is applied I would like to discuss how we can re-write the coms handler.

**Comment by rcunrau** [comment]
I may have to take your word for it. When I try to start up the Bulk dispatcher it dies as soon as the CMD dispatcher connects. I can't start the CMD dispatcher first because it never tries to connect to anything once it has started. I looked at where the Bulk dispatcher is dying, and it's in a libc::poll where it's looking at IpcServers that have connected. Except servers don't connect, only clients connect. So I looked in Bulk dispatcher main and it's a server for CMD dispatcher, which is right, but it's also a server for COMS, which probably isn't right. Anyway, if you have some small patch that you say makes it run, can you apply it and merge my PR? Then I can move on and start fixing all these things that are already working. Thanks!

**Comment by DrakBoul** [comment]
> I may have to take your word for it. When I try to start up the Bulk dispatcher it dies as soon as the CMD dispatcher connects. I can't start the CMD dispatcher first because it never tries to connect to anything once it has started. I looked at where the Bulk dispatcher is dying, and it's in a libc::poll where it's looking at IpcServers that have connected. Except servers don't connect, only clients connect. So I looked in Bulk dispatcher main and it's a server for CMD dispatcher, which is right, but it's also a server for COMS, which probably isn't right. Anyway, if you have some small patch that you say makes it run, can you apply it and merge my PR? Then I can move on and start fixing all these things that are already working. Thanks!

Okay, I can add the fix and merge after work.

**Comment by DrakBoul** [comment]
> I may have to take your word for it. When I try to start up the Bulk dispatcher it dies as soon as the CMD dispatcher connects. I can't start the CMD dispatcher first because it never tries to connect to anything once it has started. I looked at where the Bulk dispatcher is dying, and it's in a libc::poll where it's looking at IpcServers that have connected. Except servers don't connect, only clients connect. So I looked in Bulk dispatcher main and it's a server for CMD dispatcher, which is right, but it's also a server for COMS, which probably isn't right. Anyway, if you have some small patch that you say makes it run, can you apply it and merge my PR? Then I can move on and start fixing all these things that are already working. Thanks!

Yeah I'm seeing some issues when I try to uplink a command to the DFGM, sometimes it works and other times it cannot connect to the cmd dispatcher. Uplinking a command to the UHF works everytime though, so we can just use that until the DFGM gets fixed because I don't feel like fixing someone elses code.

**Review by DrakBoul — APPROVED** [review]
Added a tempory fix to get both downlink and uplink working. something is still weird with the DFGM, only 80 percent of the time it works properly. I've been using UHF as an uplink test (Change beacon from BEACON to BACON with this command: UHF 4 BACON).

**Pull request merged**
