### PR TITLE
Basic shell_handler

### PR DESCRIPTION
**Pull request by shellbertt**
Outline and combine with cmd_handler

Next need to look into:
* creating an opcode
* adding support for strings as input to an op
* then can look at launching a process given the sent message and sending back its stdout

### CODE REVIEW

**Review by rcunrau — COMMENTED** [review]
Great work! Where are we on the clippy suggestions? I clicked "Request Changes" in the hopes we'll incorporate those suggestions. If they're too difficult now I can change to 'Approve' and do the fix-up later

**Comment by rrasmuss4200** [comment]
Yup, it's able to receive any opcodes that get sent it's way. I wonder, does it need to have an opcode? If it's just executing whatever the command is in the body of the msg that it receives.

**Comment by shellbertt** [comment]
I changed to hold onto msg_dispatcher_interface as Option.

**Comment by shellbertt** [comment]
> Great work! Where are we on the clippy suggestions? I clicked "Request Changes" in the hopes we'll incorporate those suggestions. If they're too difficult now I can change to 'Approve' and do the fix-up later

Hmm I can't see where you're talking about with the "Request Changes". I pushed since then so maybe they went away, I looked in the clippy suggestions and don't see any related to my change but I can clean up a few of them

**Comment by shellbertt** [comment]
> Yup, it's able to receive any opcodes that get sent it's way. I wonder, does it need to have an opcode? If it's just executing whatever the command is in the body of the msg that it receives.

If you're referring to my "to look into" then I agree we could have it do the same no matter what opcode it receives. I will just document that in the spreadsheet then. Perhaps we will have some special actions for some opcodes one day though.

**Review by rcunrau — APPROVED** [review]
I think it's better to merge this now, rather than wait until the nix::socket changes are in.

**Pull request merged**
