### PR TITLE
Shell Handler functionality

### PR DESCRIPTION
**Pull request by shellbertt**
cli_ground_station
    - take a string as the message body coms_handler
    - add server that listens to handler messages and sends to ground_station
    - clear message buffer properly
    - etc. typos, move constant declaration, mark unreachable code
 shell_handler
    - execute command body from ground station and send back stdout
    - add client to talk to gs message server
    - switch to logging instead of println!
Msg
    - use msg_len in MsgHeader to construct message without trailing nulls

### CODE REVIEW

**Comment by shellbertt** [comment]
What should I be putting for my msg_id and msg_opcode for the return message to the GS?

**Comment by shellbertt** [comment]
What should I do when the stdout of a command doesn't fit in a single message body? Currently I send multiple messages containing chunks of the output but maybe we ought to truncate? If chunking is desired maybe we should make a way to combine multiple messages bodies together when we display them, maybe by same msg_id if that is what it is meant for?

**Comment by rrasmuss4200** [comment]
> What should I be putting for my msg_id and msg_opcode for the return message to the GS?

I Put the GS as the destination (DestID 7 I believe?) and right now there's no opcode for downlinked messages so just put it as zero.

**Comment by rrasmuss4200** [comment]
> What should I do when the stdout of a command doesn't fit in a single message body? Currently I send multiple messages containing chunks of the output but maybe we ought to truncate? If chunking is desired maybe we should make a way to combine multiple messages bodies together when we display them, maybe by same msg_id if that is what it is meant for?

Ya the same msg_id sounds like a good idea for displaying. Good question about the downlinking of multiple messages. Right now the only protocol we have for that is bulk_downlink with is like a special command in itself, but if you just send multiple messages as a response, the ground station is always polling for data so it should be ok.

**Review by rrasmuss4200 — APPROVED** [review]
Shell handler has great functionality! Will merge my branch after to incorporate it into main stack

**Pull request merged**
